IMPLEMENTATION MODULE FRV;

        (****************************************************************)
        (*                                                              *)
        (*                     ffind version number                     *)
        (*                                                              *)
        (*    Last edited:    26 October 2019                           *)
        (*    Status:         OK                                        *)
        (*                                                              *)
        (****************************************************************)


        (* NO CODE IN THIS MODULE *)


END FRV.

